---
- name: Verify
  hosts: all
  tasks:
    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Check file states
      ansible.builtin.stat:
        path: "{{ item }}"
      loop:
        - /var/log/auth.log
        - /etc/fail2ban/jail.local
        - /etc/fail2ban/fail2ban.local
      register: file_stats

    - name: Assert files exist
      ansible.builtin.assert:
        that: item.stat.exists
        fail_msg: "{{ item.item }} does not exist"
      loop: "{{ file_stats.results }}"

    - name: Assert auth.log has correct group
      ansible.builtin.assert:
        that: file_stats.results[0].stat.gr_name == expected_group
        fail_msg: "auth.log has incorrect group"
      vars:
        expected_group: >-
          {{ 'adm' if ansible_facts['os_family'] == 'Debian' else 'root' }}

    - name: Assert fail2ban is installed
      ansible.builtin.assert:
        that: "'fail2ban' in ansible_facts.packages"
        fail_msg: "fail2ban is not installed"

    - name: Assert fail2ban service is running and enabled
      ansible.builtin.assert:
        that:
          - ansible_facts.services['fail2ban.service'].state == 'running'
          - ansible_facts.services['fail2ban.service'].status == 'enabled'
        fail_msg: "fail2ban service is not running or not enabled"
